<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net8.0</TargetFramework>
	</PropertyGroup>

	<ItemGroup>
		<ProjectReference Include="..\Pcf.GivingToCustomer.Core\Pcf.GivingToCustomer.Core.csproj" />
	</ItemGroup>
	<ItemGroup>
		<Protobuf Include="protos\customer.proto" GrpcServices="Server" />
	</ItemGroup>
	<ItemGroup>
		<PackageReference Include="Grpc.AspNetCore" Version="2.76.0" />
		<PackageReference Include="Grpc.Tools" Version="2.78.0">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
		<PackageReference Include="Microsoft.Extensions.Hosting" Version="10.0.1" />
		<PackageReference Include="RabbitMQ.Client" Version="7.2.0" />
	</ItemGroup>
</Project>
